<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260119125050 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE widget (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, filter_type VARCHAR(255) DEFAULT NULL, filter_value VARCHAR(255) DEFAULT NULL, position INT NOT NULL, page INT NOT NULL, page_size INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_85F91ED07E3C61F9 ON widget (owner_id)');
        $this->addSql('ALTER TABLE widget ADD CONSTRAINT FK_85F91ED07E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE widget DROP CONSTRAINT FK_85F91ED07E3C61F9');
        $this->addSql('DROP TABLE widget');
    }
}
